function getMemorial() { return `<h1>A Memorial Service</h1>
<p>I AM the resurrection and the life, saith the Lord: he that believeth in me, though he were dead, yet shall he live: and whosoever liveth and believeth in me shall never die.<i>&mdash;St. John 11:25, 26</i></p>
<p>I KNOW that my Redeemer liveth, and that he shall stand at the latter day upon the earth. And though after my skin worms destroy this body, yet in my flesh shall I see God: whom I shall see for myself, and mine eyes shall behold, and not another.<i>&mdash;Job 19:25-27</i></p>
<p>WE brought nothing into this world, and it is certain we can carry nothing out. The Lord gave, and the Lord hath taken away; blessed be the Name of the Lord.<i>&mdash;1 Tim. 6:7, Job 1:21</i></p>
    
<h2>Psalm 90:1-10, 12</h2>
<p>LORD, thou hast been our refuge, * from one generation to another.
    Before the mountains were brought forth, or ever the earth and the world were made, * thou art God from everlasting, and world without end.
    Thou turnest man to destruction; * again thou sayest, Come again, ye children of men.
    For a thousand years in thy sight are but as yesterday, when it is past, * and as a watch in the night.
    As soon as thou scatterest them they are even as a sleep; * and fade away suddenly like the grass.
    In the morning it is green, and groweth up; * but in the evening it is cut down, dried up, and withered.
    For we consume away in thy displeasure, * and are afraid at thy wrathful indignation.
    Thou hast set our misdeeds before thee; * and our secret sins in the light of thy countenance.
    For when thou art angry all our days are gone: * we bring our years to an end, as it were a tale that is told.
    The days of our age are threescore years and ten; and though men be so strong that they come to fourscore years, * yet is their strength then but labour and sorrow; so soon passeth it away, and we are gone.
    So teach us to number our days, * that we may apply our hearts unto wisdom.</p>
    <p>Glory be to the Father, and to the Son, * and to the Holy Ghost;<br>
    As it was in the beginning, is now, and ever shall be, * world without end. Amen.</p>

    <h2>1 Corinthians 15:20-28, 35-58</h2>
<p>NOW is Christ risen from the dead, and become the firstfruits of them that slept. For since by man came death, by man came also the resurrection of the dead. For as in Adam all die, even so in Christ shall all be made alive. But every man in his own order: Christ the firstfruits; afterward they that are Christ's at his coming. Then cometh the end, when he shall have delivered up the kingdom to God, even the Father; when he shall have put down all rule and all authority and power. For he must reign, till he hath put all enemies under his feet. The last enemy that shall be destroyed is death. For he hath put all things under his feet. But when he saith all things are put under him, it is manifest that he is excepted, which did put all things under him. And when all things shall be subdued unto him, then shall the Son also himself be subject unto him that put all things under him, that God may be all in all.</p>
    <p>But some man will say, How are the dead raised up? and with what body do they come? Thou fool, that which thou sowest is not quickened, except it die: and that which thou sowest, thou sowest not that body that shall be, but bare grain, it may chance of wheat, or of some other grain: but God giveth it a body as it hath pleased him, and to every seed its own body. All flesh is not the same flesh: but there is one kind of flesh of men, another flesh of beasts, another of fishes, and another of birds. There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another. There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory. So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption: it is sown in dishonour; it is raised in glory: it is sown in weakness; it is raised in power: it is sown a natural body; it is raised a spiritual body. There is a natural body, and there is a spiritual body. And so it is written, The first man Adam was made a living soul; the last Adam was made a quickening spirit. Howbeit that was not first which is spiritual, but that which is natural; and afterward that which is spiritual. The first man is of the earth, earthy: the second man is the Lord from heaven. As is the earthy, such are they also that are earthy: and as is the heavenly, such are they also that are heavenly. And as we have borne the image of the earthy, we shall also bear the image of the heavenly.</p>
    <p>Now this I say, brethren, that flesh and blood cannot inherit the kingdom of God; neither doth corruption inherit incorruption. Behold, I shew you a mystery: We shall not all sleep, but we shall all be changed, in a moment, in the twinkling of an eye, at the last trump, (for the trumpet shall sound,) and the dead shall be raised incorruptible, and we shall be changed. For this corruptible must put on incorruption, and this mortal must put on immortality. So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality; then shall be brought to pass the saying that is written, Death is swallowed up in victory. O death, where is thy sting? O grave, where is thy victory? The sting of death is sin, and the strength of sin is the law. But thanks be to God, which giveth us the victory through our Lord Jesus Christ. Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.</p>
<hr> 
<p>MAN that is born of a woman hath but a short time to live, and is full of misery. He cometh up, and is cut down, like a flower; he fleeth as it were a shadow, and never continueth in one stay.<br>
    In the midst of life we are in death: of whom may we seek for succour, but of thee, O Lord, who for our sins art justly displeased?<br>
    Yet, O Lord God most holy, O Lord most mighty, O holy and most merciful Saviour, deliver us not into the bitter pains of eternal death.<br>
    Thou knowest, Lord, the secrets of our hearts; shut not thy merciful ears to our prayer; but spare us, Lord most holy, O God most mighty, O holy and merciful Saviour, thou most worthy judge eternal, suffer us not, at our last hour, for any pains of death, to fall from thee.</p>

    <p>I HEARD a voice from heaven, saying unto me, Write, From henceforth blessed are the dead who die in the Lord: even so saith the Spirit; for they rest from their labours.<i>—Revelation 14:13</i></p>

    <p>LORD, have mercy upon us.<br>
   <b>Christ, have mercy upon us.</b><br>
      Lord, have mercy upon us.</p>

<p>OUR Father, who art in heaven, Hallowed be thy Name. Thy kingdom come. Thy will be done on earth, As it is in heaven. Give us this day our daily bread. And forgive us our trespasses, As we forgive those who trespass against us. And lead us not into temptation; But deliver us from evil. Amen.</p>

<p>ALMIGHTY God, with whom do live the spirits of them that depart hence in the Lord, and with whom the souls of the faithful, after they are delivered from the burden of the flesh, are in joy and felicity: We give thee hearty thanks, for that it hath pleased thee to deliver our departed brethren <I>[this our brother]</I> out of the miseries of this sinful world; beseeching thee, that it may please thee, of thy gracious goodness, shortly to accomplish the number of thine elect, and to hasten thy kingdom; that we, with all those that are departed in the true faith of thy holy Name, may have our perfect consummation and bliss, both in body and soul, in thy eternal and everlasting glory; through Jesus Christ our Lord. Amen.</p>

<p>O MERCIFUL God, the Father of our Lord Jesus Christ, who is the resurrection and the life; in whom whosoever believeth shall live, though he die; and whosoever liveth, and believeth in him, shall not die eternally; who also hath taught us, by his holy Apostle Saint Paul, not to be sorry, as men without hope, for them that sleep in him: We meekly beseech thee, O Father, to raise us from the death of sin unto the life of righteousness; that, when we shall depart this life, we may rest in him, <i>[as our hope is this our brother doth;]</i> and that, at the general Resurrection in the last day, we may be found acceptable in thy sight; and receive that blessing, which thy well-beloved Son shall then pronounce to all that love and fear thee, saying, Come, ye blessed children of my Father, receive the kingdom prepared for you from the beginning of the world: Grant this, we beseech thee, O merciful Father, through Jesus Christ, our Mediator and Redeemer. Amen.</p>
<p>MAY Almighty God, the Father, the Son, and the Holy Ghost, bless us and keep us, now and for evermore. Amen.</p>`;}
