function getDayName(liturgicalDate) {
    return dayNames[liturgicalDate];
}

const dayNames = {
    "A1": "Advent Sunday",
    "A2": "The Second Sunday In Advent",
    "A3": "The Third Sunday In Advent",
    "A4": "The Fourth Sunday In Advent",
    "Xmas": "Christmas",
    "Stephen": "St. Stephen",
    "JohnEvangelist": "St. John the Evangelist",
    "Innocents": "The Holy Innocents",
    "X1": "The Sunday after Christmas",
    "Circ": "The Circumcision of Christ",
    "Epiphany": "The Epiphany",
    "E1": "The Sunday After Epiphany",
    "E2": "The Second Sunday After Epiphany",
    "E3": "The Third Sunday After Epiphany",
    "E4": "The Fourth Sunday After Epiphany",
    "E5": "The Fifth Sunday After Epiphany",
    "E6": "The Sixth Sunday After Epiphany",
    "LXX": "Septuagesima",
    "LX": "Sexagesima",
    "L": "Quinquagesima",
    "AW": "Ash Wednesday",
    "L1": "The First Sunday In Lent",
    "L2": "The Second Sunday In Lent",
    "L3": "The Third Sunday In Lent",
    "L4": "The Fourth Sunday In Lent",
    "L5": "Passion Sunday",
    "Palm": "Palm Sunday",
    "HW-Mon": "Monday Before Easter",
    "HW-Tue": "Tuesday Before Easter",
    "HW-Wed": "Wednesday Before Easter",
    "HW-Thu": "Maundy Thursday",
    "GF": "Good Friday",
    "EE": "Easter Even",
    "Easter": "Easter",
    "EasterMon": "Easter Monday",
    "EasterTue": "Easter Tuesday",
    "Ea1": "Low Sunday",
    "Ea2": "Good Shepherd Sunday",
    "Ea3": "The Third Sunday After Easter",
    "Ea4": "The Fourth Sunday After Easter",
    "Ea5": "Rogation Sunday",
    "Ascension": "Ascension Day",
    "Asc1": "The Sunday After the Ascension",
    "Whitsun": "Whitsunday",
    "Whitmon": "Whitmonday",
    "WhitTue": "Tuesday In Whitsun Week",
    "Trinity": "Trinity Sunday",
    "T1": "The Sunday After Trinity",
    "T2": "The Second Sunday After Trinity",
    "T3": "The Third Sunday After Trinity",
    "T4": "The Fourth Sunday After Trinity",
    "T5": "The Fifth Sunday After Trinity",
    "T6": "The Sixth Sunday After Trinity",
    "T7": "The Seventh Sunday After Trinity",
    "T8": "The Eighth Sunday After Trinity",
    "T9": "The Ninth Sunday After Trinity",
    "T10": "The Tenth Sunday After Trinity",
    "T11": "The ELeventh Sunday After Trinity",
    "T12": "The Twelfth Sunday After Trinity",
    "T13": "The Thirteenth Sunday After Trinity",
    "T14": "The Fourteenth Sunday After Trinity",
    "T15": "The Fifteenth Sunday After Trinity",
    "T16": "The Sixteenth Sunday After Trinity",
    "T17": "The Seventeenth Sunday After Trinity",
    "T18": "The Eighteenth Sunday After Trinity",
    "T19": "The Nineteenth Sunday After Trinity",
    "T20": "The Twentieth Sunday After Trinity",
    "T21": "The Twenty-first Sunday After Trinity",
    "T22": "The Twenty-second Sunday After Trinity",
    "T23": "The Twenty-third Sunday After Trinity",
    "T24": "The Twenty-fourth Sunday After Trinity",
    "T25": "The Twenty-fifth Sunday After Trinity",
    "T26": "The Twenty-sixth Sunday After Trinity",
    "SNBA": "Stir-Up Sunday",
    "Andrew": "St. Andrew",
    "Thomas": "St. Thomas",
    "Paul": "Conversion of St. Paul",
    "Candlemas": "Candlemas",
    "Matthias": "St. Matthias",
    "Annunciation": "Annunciation Day",
    "Mark": "St. Mark",
    "PhilipAndJames": "SS. Philip and James",
    "Barnabas": "St. Barnabas",
    "JohnBaptist": "St. John Baptist",
    "Peter": "St. Peter",
    "James": "St. James",
    "Bartholomew": "St. Bartholomew",
    "Matthew": "St. Matthew",
    "Michael": "Michaelmas",
    "Luke": "St. Luke",
    "SimonAndJude": "SS. Simon and Jude",
    "AllSaints": "All Saints",
    "ThanksgivingDay": "Thanksgiving Day",
    "IndependenceDay": "Independence Day"
};
